# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39aacbff857be520a316b20a72da637e787967bc3f7c232812e1eb68ce8bd63b3e58c9b9c50e47e6032066603eaffef23ad48e9812bb07940ecd2adc931c4afa

test:
  secret_key_base: 7f64b0c09221512f34156ee29f890efda2abe9e65e1d2d3c71bd7511dd073ea97d57a3d3cfae8134cc55f6643108e6bbce87596777327b87dda248c6535f3e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
